### ISSUE TITLE
更新後植物資料全部消失

### ISSUE THREAD

**Issue by HeyNight0712** [SlimefunGuguProject/Cultivation#17]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Cultivation/issues)，且没有找到相同的问题

### 问题描述

當更新差件版本 
Cultivation-Build 1 zh-CN(SlimefunGuguProject) (git c68752c) 到
Cultivation-Build 3 zh-CN(SlimefunGuguProject) (git 6102f08)
時
所有已放置的 植物將無法進行任何互動 除非是放置新的植物 舊植物也無法拆除 整個卡在那
![image](https://github.com/SlimefunGuguProject/Cultivation/assets/97263430/62671671-2127-4aa4-b0d8-573ae163acd8)

### 复现步骤

1.更新插件
2.重啟伺服器

### 预期行为

是不是沒有正式儲存到這個資料 我找不到這個植物的data在哪

### 服务器日志

https://paste.guizhanss.net/H2kck

### 服务端软件

Paper

### Minecraft 版本

1.19.4

### Slimefun版本

Slimefun-v2023.06-release
![image](https://github.com/SlimefunGuguProject/Cultivation/assets/97263430/81298878-9b6c-4e5e-8b8b-408399134c85)

### 插件版本

6102f08

**Comment by ybw0014** [comment]
日志里用的是2023.02版本，你的数据应该在Cultivation更新后但Slimefun没更新时被Slimefun因为报错全删了。尝试找回备份，并同时更新本体与附属。

**Comment by HeyNight0712** [comment]
找回備份 但每當更新完畢之後 他會直接 一直顯示抱錯
```
[22:40:53 ERROR]: [Slimefun] 迁移方块时发生错误: world;-349;63;1339
java.lang.IllegalStateException: There already a block in this location: world;-349:63:1339
        at com.xzavier0722.mc.plugin.slimefun4.storage.controller.SlimefunChunkData.createBlockData(SlimefunChunkData.java:39) ~[Slimefun-v2
023.06-release.jar:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.controller.BlockDataController.createBlock(BlockDataController.java:103) ~[Slimefun-v
2023.06-release.jar:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.migrator.BlockStorageMigrator.migrateBlock(BlockStorageMigrator.java:131) ~[Slimefun-
v2023.06-release.jar:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.migrator.BlockStorageMigrator.migrateWorld(BlockStorageMigrator.java:118) ~[Slimefun-
v2023.06-release.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.migrator.BlockStorageMigrator.migrateData(BlockStorageMigrator.java:59) ~[Slimefun-v2
023.06-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.core.commands.subcommands.MigrateCommand.lambda$onExecute$1(MigrateCommand.java:44) ~[Slimefun
-v2023.06-release.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-538]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        ```

**Comment by HeyNight0712** [comment]
如果說真的無法 遷移 那有方式可以移除 舊的模型嗎

**Comment by HeyNight0712** [comment]
> 



> 如果說真的無法 遷移 那有方式可以移除 舊的模型嗎

喔喔 找到了
